### ISSUE TITLE
bug in td_value_at

### ISSUE THREAD

**Issue by tvondra** [ajwerner/tdigestc#2]
I think this code in `td_value_at` is buggy:

~~~
     if (right) {
          nl = n;
          nr = &h->nodes[i+1];
          k += (n->count/2);
     } else {
          nl = &h->nodes[i-1];
          nr = n;
          k -= (n->count/2);
     }
~~~

The problem is that the second branch subtracts count for node that was not yet added to the running sum, while it should be subtracting `nl->count/2`.

It's easy to demonstrate the effect using this simple example:

~~~
void main(void)
{
	int i;
	td_histogram_t *td = td_new(20);

	for (i = 0; i < 10000; i++)
	{
		double val = (double) random() / RAND_MAX;
		td_add(td, val, 1.0);
	}

	merge(td);

	for (i = 1; i < 100; i++)
	{
		double perc = (double) i / 100.0;
		double val = td_value_at(td, perc);

		printf("%.2f	%.3f\n", perc, val);
	}

}
~~~

which simply builds a tdigest on 10000 random values (uniform distribution on [0.0, 1.0]) and then prints the percentiles. It's easy to get results like this:

~~~
0.01	0.013
0.02	0.027
0.03	0.049
0.04	0.054
0.05	0.091
0.06	0.105
0.07	0.120
0.08	0.109
0.09	0.118
0.10	0.209
...
~~~

i.e. the quantile goes up to 0.120 at 7%, and then down to 0.109 at 8% which is impossible.

Replacing the line with `k -= (nl->count/2);` fixes this.

**Comment by ajwerner** [comment]
Indeed, indeed. I've not been paying much attention at all to this repo. I wrote it more as an experiment in usability of building a C library and then wrapping it for other languages. I don't know that I was all that happy with the outcome from that perspective.

In the meantime I did spend a bit of time working a go version (https://github.com/ajwerner/tdigest). This bug was present there too and has now been fixed and the testing suite augmented to check for this invariant. I hadn't really been testing with small compression sizes which is where this bug is especially present. The test suite there is pretty generic so it shouldn't be hard to run the accuracy tests on this code. I'll try to adopt it. 

If you don't mind my asking, what have you been using this for? Other than this bug how has the experience been? What would you like to see improved?
